Spring:
  profiles:
    active: local

media:
  base:
    dir: C:\\Users\\JY\\Desktop\\code\\vuesta-

videostream:
  base:
    dir: file:C:\\Users\\JY\\Desktop\\code\\vuesta-video\\

spring:
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 60MB
