server:
  port: 3000
Spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/vuestadb;auto_server=true
    username: test
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # boot2.5부터 변경아래 sql.init.과 병행하는 것을 권장하지 않음.

  sql:
    init:
      encoding: UTF-8
      mode: always
      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql

mybatis:
  type-aliases-package: com.cf.vuestagram.dto
